# base image
# FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04
FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04

# maintainer
LABEL email="bch0322@gmail.com"

# set timezone
ENV TZ="Asia/Seoul"
RUN apt-get update && DEBIAN_FRONTEND=noninterative apt-get install tzdata
RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata
    
# Remove any third-party apt sources to avoid issues with expiring keys.
RUN rm -f /etc/apt/sources.list.d/*.list

# Install some basic utilities
RUN apt-get update && apt-get -y --no-install-recommends install \
        sudo \
        git \
        bzip2 \
        curl \
        wget \
        ca-certificates \
        python3-dev \
        python3-pip \
        build-essential \
        libgl1-mesa-glx \
        libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Install requirements
COPY requirements/requirements_base.txt /requirements_base.txt
RUN pip3 --no-cache-dir install -r /requirements_base.txt

# 설치로 생성된 캐시 파일들을 삭제해서 용량 줄이기!
RUN apt-get clean && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/cache/* && \
    rm -rf /var/lib/log/*

# Set the default command to python3
CMD ["/bin/bash"]
